Support editing multi-line annotations (Closes: #2283)
GothenburgBitFactory/taskwarrior pull request #2383
Opened 2021-01-05 17:27 UTC by jspricke

#### Description

Since e4b9c1f annotations where JSON encoded in task edit to escape
new lines (\n). But other strings where mangled as well, like https://
becoming https:\/\/, making it hard to edit.

This patch removes the JSON encoding and indents new lines instead.

#### Additional information...

- [X] Have you run the test suite?
Failed:

Unexpected successes:

Skipped:
dependencies.t                      3
export.t                            1
feature.default.project.t           4
hooks.on-modify.t                   1
import.t                            1
recurrence.t                        1
tw-1999.t                           2
wait.t                              1

Expected failures:
dependencies.t                      2
filter.t                            4
hyphenate.t                         1
lexer.t                             4
project.t                           1
quotes.t                            1
search.t                            1

2021-01-06 03:57 UTC, tbabej requested changes
Tested and looks amazing! Two general comments:
* There should be no need to implement a new string replacement method, I believe `str_replace` [available from libshared's shared.cpp](https://github.com/GothenburgBitFactory/libshared/blob/a9226163/src/shared.cpp#L140) performs the same task.
* (Optional) Ideally, we'd also add a test for CmdEdit. Test suite so far has no test being able to fake actions takein in the `EDITOR` window, but I believe with bash_tap.sh interface it should be doable (i.e. see [an example of bash test here](https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/test/tw-1718.t)).

2021-01-06 09:06 UTC, jspricke commented
> * There should be no need to implement a new string replacement method, I believe `str_replace` [available from libshared's shared.cpp](https://github.com/GothenburgBitFactory/libshared/blob/a9226163/src/shared.cpp#L140) performs the same task.

No idea how I could have missed that, thanks! Updated.

> * (Optional) Ideally, we'd also add a test for CmdEdit. Test suite so far has no test being able to fake actions takein in the `EDITOR` window, but I believe with bash_tap.sh interface it should be doable (i.e. see [an example of bash test here](https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/test/tw-1718.t)).

There is one test already here: https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/test/edit.t#L62

2021-01-08 03:36 UTC, tbabej commented
Thanks for editing the PR!

> There is one test already here.
I meant a test that would specifically test what we added here, but I think it would be more tricky than the example already given in the codebase. I can add that myself as I already have an idea how to go about it.

2021-01-08 03:36 UTC, tbabej approved these changes

2021-01-08 03:37 UTC, merged