Implement hooks in XDG_CONFIG_HOME by default
GothenburgBitFactory/taskwarrior pull request #2438
Opened 2021-04-03 18:32 UTC by jdorel

#### Description

Implement hooks in XDG_CONFIG_HOME by defalt

#### Additional information...

- [X] Have you run the test suite?

Currently one problem : 
```
Failed:                        
version.t                           1
```
No idea of how to resolve it

2021-04-03 18:43 UTC, tbabej commented
Hi @jdorel, thanks for looking into this!

The `version.t` problem just means the tests were build with older "commit" than the task binary being tested itself. It serves more as a warning - as you can see, in the CI all the platforms successfully passed.

2021-04-03 19:01 UTC, tbabej requested changes

2021-04-05 07:53 UTC, jdorel commented on src/util.h
> +const std::string getDefaultHooksLocation();
Indeed

2021-04-05 08:02 UTC, jdorel commented on src/util.cpp
> +  return format ("{1}/task/hooks", getXdgConfigHome());
I implemented the logic in `Hooks.cpp`, but you are right that it should be implemented in `utils.cpp`,

2021-04-05 08:05 UTC, jdorel commented on src/util.cpp
> +  return format ("{1}/task/hooks", getXdgConfigHome());
Maybe the full implementation should be in a function `getHooksLocation` in `Hooks.cpp` or in `Context.cpp` ?

2021-04-05 08:09 UTC, jdorel commented on src/Hooks.cpp
> +    if (Context::getContext ().rc_file.exists ())
I didn't want to hardcode the path in two different location, but I didn't realize that `rc_file` was modified during context initialization.

2021-04-14 07:12 UTC, tbabej commented
Looks like the latest set of changes here broke the tests for hooks :crying_cat_face:

2021-04-15 16:54 UTC, jdorel reviewed
@tbabej Updated the test suite + fixed a bug

2021-04-15 16:54 UTC, jdorel commented on src/commands/CmdShow.cpp
> -          i.first.substr (0,  5) != "hook."                 &&
@tbabej Fixed an error in config verification

2021-04-15 16:54 UTC, jdorel commented on test/basetest/task.py
> +                     "hooks.location={1}\n"
@tbabej Fix test suite : specify `hooks.location`, otherwise search in ~/.config/task

2024-03-02 21:27 UTC, djmitche commented
@jdorel would you like to rebase this and we can get it merged?

2024-05-06 00:04 UTC, closed without merging