Implement multi-day holidays
GothenburgBitFactory/taskwarrior pull request #2457
Opened 2021-04-18 22:16 UTC by DanielMowitz

#### Description

This PR resolves #1911 and cleans up the code for holiday colorization.

#### Additional information...

- [x] Have you run the test suite?
Output of test/problems:
```errors
Failed:
template.t                          2
version.t                           1

Unexpected successes:

Skipped:
dependencies.t                      1
export.t                            1
feature.default.project.t           4
hooks.on-modify.t                   1
import.t                            1
recurrence.t                        1
template.t                          3
tw-1999.t                           2
wait.t                              1

Expected failures:
dependencies.t                      3
filter.t                            3
hyphenate.t                         1
lexer.t                             4
quotes.t                            1
template.t                          1
tw-2124.t                           1
```

2021-04-21 01:07 UTC, tbabej requested changes
Looks good! I left suggestions for some minor changes in the code (mostly around readability), but most importantly, we'll need to:
* add a test or two to make sure this works (at least a sanity check verifying that holidays with start and end do not make task calendar crash)
* documentation changes in the relevant sections of man pages for `task` and `taskrc`

2021-04-21 01:07 UTC, tbabej commented on src/commands/CmdCalendar.cpp
> +                Datetime holEnd   (end.c_str (), Context::getContext ().config.get ("dateformat.holiday"));
Perhaps we could move `Context::getContext ().config.get ("dateformat.holiday")` into its own variable? Gets quite repetitive over the code. Would be a nice refactoring win coming for this PR :slightly_smiling_face:

2021-04-21 01:07 UTC, tbabej commented on src/commands/CmdCalendar.cpp
> +				}
This looks like runaway indentation (same with opening bracket).

2021-04-21 01:07 UTC, tbabej commented on src/commands/CmdCalendar.cpp
> +				}
Fixed in subsequent commit.

2021-04-21 11:29 UTC, DanielMowitz commented on src/commands/CmdCalendar.cpp
>              auto holName = Context::getContext ().config.get ("holiday." + it.first.substr (8, it.first.size () - 13) + ".name");
You're right, this is a good place to start with that.

2021-04-21 21:00 UTC, DanielMowitz commented
This should cover all requested changes. I'm not quite content with the comment on the tests though.

2021-04-22 02:23 UTC, merged

2021-04-22 02:23 UTC, tbabej commented
Looks good to me. Thanks for the PR, @DanielMowitz !