Build in parallel, test sequentially
GothenburgBitFactory/taskwarrior pull request #3502
Opened 2024-06-21 12:49 UTC by djmitche

It seems the tests fail with SIGABRT when run with `-j 8` - perhaps there's just too much going on for a 4-thread processor to keep up? Or perhaps the tests interfere with each other? So, this removes the parallelism from tests.

However, _building_ in parallel should be fine, so let's do that.

2024-06-21 12:56 UTC, felixschurk commented
https://github.com/GothenburgBitFactory/taskwarrior/pull/3483#issuecomment-2182696577

Maybe to have it easier to talk about.

2024-06-21 13:14 UTC, felixschurk commented
Maybe checking it out with having the systems building automatically with maximum parallelism (build no argument, as Ninja is parallel)
> Builds are always run in parallel, based by default on the number of CPUs your system has. Underspecified build dependencies will result in incorrect builds - From Ninja - Manual

And using for CMake also the `--parallel` flag, as of CMake/CTest 2.29 which should also just use the possible maximum number? https://cmake.org/cmake/help/latest/manual/ctest.1.html#cmdoption-ctest-j

2024-06-22 19:19 UTC, felixschurk requested changes

2024-06-22 19:19 UTC, felixschurk commented on .github/workflows/tests.yaml
> +        run: cmake --build build -j 8 --target build_tests
Here `-j 8` is not needed as this build is with Ninja.

2024-06-23 00:00 UTC, closed without merging

2024-06-23 00:00 UTC, djmitche commented
Well, the coverage failed with SIGABRT here, so I suppose this is not the right fix :(